# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

breg <- function(y, X, betabar, A) {
    .Call('_bayesmcustom_breg', PACKAGE = 'bayesmcustom', y, X, betabar, A)
}

llmnl <- function(beta, y, X) {
    .Call('_bayesmcustom_llmnl', PACKAGE = 'bayesmcustom', beta, y, X)
}

lndIWishart <- function(nu, V, IW) {
    .Call('_bayesmcustom_lndIWishart', PACKAGE = 'bayesmcustom', nu, V, IW)
}

lndMvn <- function(x, mu, rooti) {
    .Call('_bayesmcustom_lndMvn', PACKAGE = 'bayesmcustom', x, mu, rooti)
}

rmultireg <- function(Y, X, Bbar, A, nu, V) {
    .Call('_bayesmcustom_rmultireg', PACKAGE = 'bayesmcustom', Y, X, Bbar, A, nu, V)
}

rmvpGibbs_rcpp_loop <- function(R, keep, nprint, p, y, X, beta0, sigma0, V, nu, betabar, A) {
    .Call('_bayesmcustom_rmvpGibbs_rcpp_loop', PACKAGE = 'bayesmcustom', R, keep, nprint, p, y, X, beta0, sigma0, V, nu, betabar, A)
}

rwishart <- function(nu, V) {
    .Call('_bayesmcustom_rwishart', PACKAGE = 'bayesmcustom', nu, V)
}

callroot <- function(c1, c2, tol, iterlim) {
    .Call('_bayesmcustom_callroot', PACKAGE = 'bayesmcustom', c1, c2, tol, iterlim)
}

